# Generated by Django 6.0.6 on 2026-06-17 16:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0002_alter_activo_tipo_alter_activo_confidencialidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('NAT', 'Natural / Desastre'), ('HUM', 'Error humano'), ('MAL', 'Ataque malicioso / Malware'), ('TEC', 'Fallo técnico'), ('ORG', 'Organizacional / Procesos')], default='TEC', max_length=3)),
            ],
            options={
                'verbose_name': 'Amenaza',
                'verbose_name_plural': 'Amenazas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('tema', models.CharField(choices=[('ORG', 'Organizacional'), ('PER', 'Personas'), ('FIS', 'Físico'), ('TEC', 'Tecnológico')], default='ORG', max_length=3)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Control ISO 27002',
                'verbose_name_plural': 'Controles ISO 27002:2022',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Vulnerabilidad',
                'verbose_name_plural': 'Vulnerabilidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controles_existentes', models.TextField(blank=True, help_text='Controles ya implementados antes del análisis.')),
                ('probabilidad', models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto', models.IntegerField(choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('estrategia', models.CharField(blank=True, choices=[('MIT', 'Mitigar'), ('TRA', 'Transferir'), ('ACE', 'Aceptar'), ('EVI', 'Evitar')], max_length=3)),
                ('responsable', models.CharField(blank=True, max_length=120)),
                ('probabilidad_residual', models.IntegerField(blank=True, choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto_residual', models.IntegerField(blank=True, choices=[(1, 'Muy Bajo'), (2, 'Bajo'), (3, 'Medio'), (4, 'Alto'), (5, 'Muy Alto')], null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones o recomendaciones para las partes interesadas.')),
                ('estado', models.CharField(choices=[('IDE', 'Identificado'), ('TRA', 'En tratamiento'), ('CON', 'Controlado'), ('CER', 'Cerrado')], default='IDE', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='activos.activo')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riesgos.amenaza')),
                ('controles_propuestos', models.ManyToManyField(blank=True, related_name='riesgos', to='riesgos.control')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='riesgos.vulnerabilidad')),
            ],
            options={
                'verbose_name': 'Riesgo',
                'verbose_name_plural': 'Riesgos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
