# Generated by Django 6.0.6 on 2026-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_datos_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='riesgo',
            name='fecha_control',
            field=models.DateField(blank=True, help_text='Fecha en que el riesgo quedó controlado/verificado.', null=True),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='fecha_tratamiento',
            field=models.DateField(blank=True, help_text='Fecha en que se aplicó el tratamiento (controles).', null=True),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='cve',
            field=models.CharField(blank=True, help_text='Identificador CVE asociado, p.ej. CVE-2021-44228 (opcional).', max_length=30, verbose_name='CVE'),
        ),
    ]
